name: Windows_IRIS_Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Create Settings File
      run: |
        $jsonContent = @{
          projectId = "${{ secrets.PROJECT_ID }}"
          jwt_auth = "${{ secrets.IRIS_JWT }}"
          framework = "netframework"
        } | ConvertTo-Json

        $jsonContent | Set-Content -Path "iris.settings.json"
        
    - name: Download IRIS Scanner CLI 
      shell: powershell
      run: Invoke-WebRequest -Uri "https://iris.codeeyesolutions.com/assets/onprem/win/v1/net/iris-scanner-cli.exe" -OutFile "iris-scanner-cli.exe"

    - name: Run Scan 
      shell: powershell
      run: |
        $env:Path += ";C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin"
        $commitId = "${{ github.sha }}"
        $shortCommitId = "PR-"+$commitId.Substring(0, 8)
        $currentDirectory = (Get-Location).Path
        $solutionFile = $currentDirectory + "\NORTHWND.sln"
        .\iris-scanner-cli.exe -s $currentDirectory -sln $solutionFile -r $shortCommitId
